title: Produkter
icon: collections
template: products/show
layout: layout
revisions: false
entry_class: DuncanMcClean\Cargo\Products\Product
route: 'produkter/{slug}'
sort_dir: asc
date_behavior:
  past: null
  future: null
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
taxonomies:
  - categories
